// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt8nIzseB1j3brS9tlqdpWw0W8GVyj6GE',
    appId: '1:926176861295:web:d4ce61566bb0e6c3c8819a',
    messagingSenderId: '926176861295',
    projectId: 'campusconnect-fce4f',
    authDomain: 'campusconnect-fce4f.firebaseapp.com',
    storageBucket: 'campusconnect-fce4f.firebasestorage.app',
    measurementId: 'G-VST15YRH6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3rhfjMATT4K1N4D1ukrj8SuLMASrxJyg',
    appId: '1:926176861295:android:fb4ff542bd4eaba5c8819a',
    messagingSenderId: '926176861295',
    projectId: 'campusconnect-fce4f',
    authDomain: 'campusconnect-fce4f.firebaseapp.com',
    storageBucket: 'campusconnect-fce4f.firebasestorage.app',
  );
}
